spring:
  datasource:
    url: jdbc:sqlserver://localhost\SQLEXPRESS;database=pizza-order-app;encrypt=true;trustServerCertificate=true
    username: sa
    password: sqlexpress
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        globally_quoted_identifiers: true
        use_nationalized_character_data: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 5MB
app:
  jwt:
    tokenHeaderKey: Authorization
    tokenPrefixName: Bearer
    secret: UGl6emFPcmRlckFwcFRlc3RTZWNyZXRGb3JKV1RBdXRoZW50aWNhdGlvbg==
    tokenExpirationInMillis: 43200000 # half day
    refreshTokenExpirationInMillis: 172800000 # 2 day

server:
  address: 0.0.0.0